# Application Configuration
spring.application.name=VolunteerWeb

server.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myssl

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/volunteer_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=kien123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=W7/9Y2eHPG+Q4C0b0Y0/xvFUPnQidTysax0J+7+EL4Mw8rfXEHmCpOKj4hvnTiP4nzLV6WcGkdmFjrnZ5jdZ2w==
jwt.expiration=86400000 
jwt.refresh.expiration=604800000


# Mail Configuration (Using Gmail as an example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kien0610minh@gmail.com
spring.mail.password=ivrt wssp oktn vprb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.test-connection=false

# WebSocket Configuration
# No specific properties needed, handled by WebSocketConfig

# Cache Configuration (Using Caffeine)
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=600s

# File Upload Configuration
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
upload.dir=uploads/

# Actuator Configuration (Monitoring)
management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enabled=true

# Web Push
vapid.publicKey=BBaLZ87GwW4SMSoMQ1TYaAVGoqgkZRL-BOjUBdh4Fy0ag_dgXAy1GQff-7Q8RMRC7IHqwGY3d5QjmXZOI11jNGM
vapid.privateKey=Cwx3S0hD6eXkj_pq3w3UXOOpuw3d3uFGcJJn4qhY3z0
vapid.subject=mailto:kien0610minh@gmail.com
